image: "maven:3.3.9-jdk-8"
services:
    - "mysql:5.7.26"
    - "mongo:4.0.4"
maven-install:
   script: "mvn install"
   stage: install
maven-test:
   script: "mvn test"
   stage: test
stages:
   - test
   - install
variables:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: SBA
   MYSQL_USER: root
   MYSQL_PASSWORD: root
   MYSQL_HOST: mysql
   MYSQL_CI_URL: jdbc:mysql://mysql:3306/SBA
